steps:
 # Build the container image
 - name: "gcr.io/cloud-builders/docker"
   args: ["build", "-t", 'us-central1-docker.pkg.dev/teatis-discovery/cloud-run-source-deploy/teatis-server', '.']
 # Push the container image to Container Registry
 - name: "gcr.io/cloud-builders/docker"
   args: ['push', 'us-central1-docker.pkg.dev/teatis-discovery/cloud-run-source-deploy/teatis-server']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '$_SERVICE_NAME'
   - '--image'
   - 'us-central1-docker.pkg.dev/teatis-discovery/cloud-run-source-deploy/teatis-server'
   - '--region'
   - '$_REGION'
   - '--platform'
   - 'managed'
images:
 - 'us-central1-docker.pkg.dev/teatis-discovery/cloud-run-source-deploy/teatis-server'
substitutions:
 _REGION: us-central1
 _SERVICE_NAME: teatis-server
