import { SurveyQuestion, SurveyQuestionImage, SurveyQuestionOption } from '@prisma/client';

interface Survey {
  label:string;
  name:string;
  questions: Question[];
}

interface Question extends Omit<SurveyQuestion, 'id' | 'createdAt' | 'updatedAt'>{
  children?:Question[];
  displayOrder?:number;
  images?:Omit<SurveyQuestionImage, 'id' | 'createdAt' | 'updatedAt' | 'surveyQuestionId'>[];
  options:Omit<SurveyQuestionOption, 'id' | 'createdAt' | 'updatedAt' | 'surveyQuestionId'>[];
}

export const seedSurvey:Survey[] = [
  {
    name: 'prePurchaseSurvey',
    label: 'Pre Purchase Survey',
    questions: [
      {
        displayOrder: 1,
        name: 'cravingAmount',
        label: 'How often do you eat snacks?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'More than once a day',
            value: null,
            isArchived: false,
          },
          {
            label: 'Once a day',
            value: null,
            isArchived: false,
          },
          {
            label: 'Few times a week',
            value: null,
            isArchived: false,
          },
          {
            label: 'Less than once a week',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 2,
        name: 'cravingIncrease',
        label: 'Has the amount of your snacking increase over time?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Yes',
            value: null,
            isArchived: false,
          },
          {
            label: 'No',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 3,
        name: 'mostCravingTime',
        label: 'When do you feel craving the most?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Bed time',
            value: null,
            isArchived: false,
          },
          {
            label: 'Before or after meal',
            value: null,
            isArchived: false,
          },
          {
            label: 'While driving',
            value: null,
            isArchived: false,
          },
          {
            label: 'While watching TV',
            value: null,
            isArchived: false,
          },
          {
            label: 'In between work',
            value: null,
            isArchived: false,
          },
          {
            label: 'Others',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 4,
        name: 'cravingReason',
        label: 'What is the main reason of your craving?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Boredom',
            value: null,
            isArchived: false,
          },
          {
            label: 'Stress',
            value: null,
            isArchived: false,
          },
          {
            label: 'Just craving',
            value: null,
            isArchived: false,
          },
          {
            label: 'Others',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 5,
        name: 'cravingSnack',
        label: 'Which snack do you crave the most?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Chocolate (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Brownies (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Ice cream (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Cookies (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Waffles (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Biscuits (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Popcorns (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Chips (savory)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Pizza (savory)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Hamburger (savory)',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 6,
        name: 'diabetes',
        label: 'What stage of Diabetes are you in?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Get the dietician’s recommendations personalized to your preference and condition by answering some questions.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Type2',
            value: null,
            isArchived: false,
          },
          {
            label: 'Type1',
            value: null,
            isArchived: false,
          },
          {
            label: 'Prediabetes',
            value: null,
            isArchived: false,
          },
          {
            label: 'Gestational Diabetes',
            value: null,
            isArchived: false,
          },
          {
            label: 'Non-Diabetic',
            value: null,
            isArchived: false,
          },
          {
            label: 'I am not sure',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 7,
        name: 'gender',
        label: 'How do you identify?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Providing your gender will help us to determine your optimal calorie intake.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Female',
            value: null,
            isArchived: false,
          },
          {
            label: 'Male',
            value: null,
            isArchived: false,
          },
          {
            label: 'Prefer not to say',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 8,
        name: 'age',
        label: 'How old are you?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Age helps us in calculate your metabolic rate.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: '~ 19',
            value: 15,
            isArchived: false,
          },
          {
            label: '20 ~ 29',
            value: 25,
            isArchived: false,
          },
          {
            label: '30 ~ 39',
            value: 35,
            isArchived: false,
          },
          {
            label: '40 ~ 49',
            value: 45,
            isArchived: false,
          },
          {
            label: '50 ~ 59',
            value: 55,
            isArchived: false,
          },
          {
            label: '60 ~ 69',
            value: 65,
            isArchived: false,
          },
          {
            label: '70 ~',
            value: 75,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 9,
        name: 'height',
        label: 'How tall are you?',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Height helps us calculate your BMI.',
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: `~ 4'9`,
            value: 145,
            isArchived: false,
          },
          {
            label: `4'9 ~ 5'1`,
            value: 155,
            isArchived: false,
          },
          {
            label: `5'2 ~ 5'5`,
            value: 165,
            isArchived: false,
          },
          {
            label: `5'6 ~ 5'8`,
            value: 175,
            isArchived: false,
          },
          {
            label: `5'9 ~ 6'1`,
            value: 185,
            isArchived: false,
          },
          {
            label: `6'2 ~ 6'5`,
            value: 195,
            isArchived: false,
          },
          {
            label: `6'6 ~`,
            value: 205,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 10,
        name: 'weight',
        label: 'How much do you weigh?',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Weight helps us calculate your BMI.',
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: '330 ~',
            value: 155,
            isArchived: false,
          },
          {
            label: '309 ~ 329',
            value: 145,
            isArchived: false,
          },
          {
            label: '287 ~ 308',
            value: 135,
            isArchived: false,
          },
          {
            label: '265 ~ 286',
            value: 125,
            isArchived: false,
          },
          {
            label: '243 ~ 264',
            value: 115,
            isArchived: false,
          },
          {
            label: '220 ~ 242',
            value: 105,
            isArchived: false,
          },
          {
            label: '198 ~ 219',
            value: 95,
            isArchived: false,
          },
          {
            label: '176 ~ 197',
            value: 85,
            isArchived: false,
          },
          {
            label: '154 ~ 175',
            value: 75,
            isArchived: false,
          },
          {
            label: '132 ~ 153',
            value: 65,
            isArchived: false,
          },
          {
            label: '~ 132',
            value: 55,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 11,
        name: 'bodyScale',
        label: 'Do you own a body scale?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Yes',
            value: null,
            isArchived: false,
          },
          {
            label: 'No',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 12,
        name: 'solutionLowGISnacks',
        label: 'Low Glucose Impact Snacks',
        isRequired: false,
        isCustomerFeature: false,
        hint: `100% human-tested snacks curated just for you! No more worrying about blood sugar spike. <br/>You can see what’s included at the end of the quiz!`,
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_carrie-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 13,
        name: 'solutionMentalCravingControl',
        label: 'Mental Craving Control',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'You will gain access to talk to our dietitian. They will guide you through your struggles and questions!',
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_charlotte-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 14,
        name: 'solutionCurriculum',
        label: 'Science-based curriculum',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Experts from medical industry, diabetes educator and dietitian has built all-in-one curriculum to help you change the way you eat!',
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_miranda-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 15,
        name: 'solutionBenefits',
        label: 'Benefit',
        isRequired: false,
        isCustomerFeature: false,
        hint: `According to a study from Cambridge University, eating a healthier snack can not only improve snacking habits but also showed a trend towards a favorable effect on glucose levels. <br/>Lastly, tell us what you like and dislike so we can personalize your box!`,
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_samantha-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 16,
        name: 'allergens',
        label: 'What kind of allergies do you have?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 17,
        name: 'ingredientDislikes',
        label: 'Which ingredients do you dislike?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
        children: [
          {
            displayOrder: 1,
            name: 'ingredientDislikesOthers',
            label: 'What other ingredients do you dislike?',
            isRequired: false,
            isCustomerFeature: true,
            hint: null,
            placeholder: 'Search and add ingredients',
            responseType: 'multiple',
            parentSurveyQuestionId: null,
            options: [],
          },
        ],
      },
      {
        displayOrder: 18,
        name: 'flavorDislikes',
        label: 'Which flavors do you dislike?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: 'Search and add flavors',
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 19,
        name: 'email',
        label: `You've reached the end of the quiz!`,
        isRequired: true,
        isCustomerFeature: true,
        hint: 'Submit your email to create your profile and get your box now!',
        placeholder: 'hi@teatismeal.com',
        responseType: 'text',
        parentSurveyQuestionId: null,
        options: [],
      },

    ],
  },
  {
    name: 'employeePrePurchaseSurvey',
    label: 'Employee Pre Purchase Survey',
    questions: [

      {
        displayOrder: 1,
        name: 'cravingAmount',
        label: 'How often do you eat snacks?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'More than once a day',
            value: null,
            isArchived: false,
          },
          {
            label: 'Once a day',
            value: null,
            isArchived: false,
          },
          {
            label: 'Few times a week',
            value: null,
            isArchived: false,
          },
          {
            label: 'Less than once a week',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 2,
        name: 'cravingIncrease',
        label: 'Has the amount of your snacking increase over time?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Yes',
            value: null,
            isArchived: false,
          },
          {
            label: 'No',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 3,
        name: 'mostCravingTime',
        label: 'When do you feel craving the most?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Bed time',
            value: null,
            isArchived: false,
          },
          {
            label: 'Before or after meal',
            value: null,
            isArchived: false,
          },
          {
            label: 'While driving',
            value: null,
            isArchived: false,
          },
          {
            label: 'While watching TV',
            value: null,
            isArchived: false,
          },
          {
            label: 'In between work',
            value: null,
            isArchived: false,
          },
          {
            label: 'Others',
            value: null,
            isArchived: false,
          },
        ],
      },

      {
        displayOrder: 4,
        name: 'cravingReason',
        label: 'What is the main reason of your craving?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Boredom',
            value: null,
            isArchived: false,
          },
          {
            label: 'Stress',
            value: null,
            isArchived: false,
          },
          {
            label: 'Just craving',
            value: null,
            isArchived: false,
          },
          {
            label: 'Others',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 5,
        name: 'cravingSnack',
        label: 'Which snack do you crave the most?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Chocolate (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Brownies (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Ice cream (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Cookies (sweet)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Waffles (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Biscuits (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Popcorns (high carbs)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Chips (savory)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Pizza (savory)',
            value: null,
            isArchived: false,
          },
          {
            label: 'Hamburger (savory)',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 6,
        name: 'diabetes',
        label: 'What stage of Diabetes are you in?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Get the dietician’s recommendations personalized to your preference and condition by answering some questions.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Type2',
            value: null,
            isArchived: false,
          },
          {
            label: 'Type1',
            value: null,
            isArchived: false,
          },
          {
            label: 'Prediabetes',
            value: null,
            isArchived: false,
          },
          {
            label: 'Gestational Diabetes',
            value: null,
            isArchived: false,
          },
          {
            label: 'Non-Diabetic',
            value: null,
            isArchived: false,
          },
          {
            label: 'I am not sure',
            value: null,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 7,
        name: 'gender',
        label: 'How do you identify?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Providing your gender will help us to determine your optimal calorie intake.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Female',
            value: null,
            isArchived: false,
          },
          {
            label: 'Male',
            value: null,
            isArchived: false,
          },
          {
            label: 'Prefer not to say',
            value: null,
            isArchived: false,
          },
        ],
      },

      {
        displayOrder: 8,
        name: 'age',
        label: 'How old are you?',
        isRequired: false,
        isCustomerFeature: false,
        hint: `Age helps us in calculate your metabolic rate.`,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: '~ 19',
            value: 15,
            isArchived: false,
          },
          {
            label: '20 ~ 29',
            value: 25,
            isArchived: false,
          },
          {
            label: '30 ~ 39',
            value: 35,
            isArchived: false,
          },
          {
            label: '40 ~ 49',
            value: 45,
            isArchived: false,
          },
          {
            label: '50 ~ 59',
            value: 55,
            isArchived: false,
          },
          {
            label: '60 ~ 69',
            value: 65,
            isArchived: false,
          },
          {
            label: '70 ~',
            value: 75,
            isArchived: false,
          },
        ],
      },

      {
        displayOrder: 9,
        name: 'height',
        label: 'How tall are you?',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Height helps us calculate your BMI.',
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: `~ 4'9`,
            value: 145,
            isArchived: false,
          },
          {
            label: `4'9 ~ 5'1`,
            value: 155,
            isArchived: false,
          },
          {
            label: `5'2 ~ 5'5`,
            value: 165,
            isArchived: false,
          },
          {
            label: `5'6 ~ 5'8`,
            value: 175,
            isArchived: false,
          },
          {
            label: `5'9 ~ 6'1`,
            value: 185,
            isArchived: false,
          },
          {
            label: `6'2 ~ 6'5`,
            value: 195,
            isArchived: false,
          },
          {
            label: `6'6 ~`,
            value: 205,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 10,
        name: 'weight',
        label: 'How much do you weigh?',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Weight helps us calculate your BMI.',
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: '330 ~',
            value: 155,
            isArchived: false,
          },
          {
            label: '309 ~ 329',
            value: 145,
            isArchived: false,
          },
          {
            label: '287 ~ 308',
            value: 135,
            isArchived: false,
          },
          {
            label: '265 ~ 286',
            value: 125,
            isArchived: false,
          },
          {
            label: '243 ~ 264',
            value: 115,
            isArchived: false,
          },
          {
            label: '220 ~ 242',
            value: 105,
            isArchived: false,
          },
          {
            label: '198 ~ 219',
            value: 95,
            isArchived: false,
          },
          {
            label: '176 ~ 197',
            value: 85,
            isArchived: false,
          },
          {
            label: '154 ~ 175',
            value: 75,
            isArchived: false,
          },
          {
            label: '132 ~ 153',
            value: 65,
            isArchived: false,
          },
          {
            label: '~ 132',
            value: 55,
            isArchived: false,
          },
        ],
      },
      {
        displayOrder: 11,
        name: 'bodyScale',
        label: 'Do you own a body scale?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'single',
        parentSurveyQuestionId: null,
        options: [
          {
            label: 'Yes',
            value: null,
            isArchived: false,
          },
          {
            label: 'No',
            value: null,
            isArchived: false,
          },
        ],
      },

      {
        displayOrder: 12,
        name: 'solutionLowGISnacks',
        label: 'Low Glucose Impact Snacks',
        isRequired: false,
        isCustomerFeature: false,
        hint: `100% human-tested snacks curated just for you! No more worrying about blood sugar spike. <br/>You can see what’s included at the end of the quiz!`,
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_carrie-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 13,
        name: 'solutionMentalCravingControl',
        label: 'Mental Craving Control',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'You will gain access to talk to our dietitian. They will guide you through your struggles and questions!',
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_charlotte-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 14,
        name: 'solutionCurriculum',
        label: 'Science-based curriculum',
        isRequired: false,
        isCustomerFeature: false,
        hint: 'Experts from medical industry, diabetes educator and dietitian has built all-in-one curriculum to help you change the way you eat!',
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_miranda-min.gif', position: 1 }],
        options: [],
      },
      {
        displayOrder: 15,
        name: 'solutionBenefits',
        label: 'Benefit',
        isRequired: false,
        isCustomerFeature: false,
        hint: `According to a study from Cambridge University, eating a healthier snack can not only improve snacking habits but also showed a trend towards a favorable effect on glucose levels. <br/>Lastly, tell us what you like and dislike so we can personalize your box!`,
        placeholder: null,
        responseType: 'noResponse',
        parentSurveyQuestionId: null,
        images: [{ src: 'https://storage.googleapis.com/teatis-images/onboarding/teatis_anime_samantha-min.gif', position: 1 }],
        options: [],
      },

      {
        displayOrder: 16,
        name: 'allergens',
        label: 'What kind of allergies do you have?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 17,
        name: 'ingredientDislikes',
        label: 'Which ingredients do you dislike?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
        children: [
          {
            displayOrder: 1,
            name: 'ingredientDislikesOthers',
            label: 'What other ingredients do you dislike?',
            isRequired: false,
            isCustomerFeature: true,
            hint: null,
            placeholder: 'Search and add ingredients',
            responseType: 'multiple',
            parentSurveyQuestionId: null,
            options: [],
          },
        ],
      },
      {
        displayOrder: 18,
        name: 'flavorDislikes',
        label: 'Which flavors do you dislike?',
        isRequired: false,
        isCustomerFeature: true,
        hint: null,
        placeholder: 'Search and add flavors',
        responseType: 'multiple',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 19,
        name: 'email',
        label: `You've reached the end of the quiz!`,
        isRequired: true,
        isCustomerFeature: true,
        hint: 'Submit your email to create your profile and get your box now!',
        placeholder: 'hi@teatismeal.com',
        responseType: 'text',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 20,
        name: 'name',
        label: 'What is your name?',
        isRequired: true,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'text',
        parentSurveyQuestionId: null,
        options: [],
      },
      {
        displayOrder: 21,
        name: 'address',
        label: 'What is your address?',
        isRequired: true,
        isCustomerFeature: true,
        hint: null,
        placeholder: null,
        responseType: 'text',
        parentSurveyQuestionId: null,
        options: [],
      },
    ],
  },
  {
    name: 'postPurchaseSurvey',
    label: 'Post Purchase Survey',
    questions: [
      {
        displayOrder: 1,
        name: 'productSatisfaction',
        label: 'How satisfied are you with ${PRODUCT_NAME}?',
        isRequired: false,
        isCustomerFeature: false,
        hint: null,
        placeholder: null,
        responseType: 'number',
        parentSurveyQuestionId: null,
        options: [],
        children: [
          {
            displayOrder: 1,
            name: 'productSatisfactionReason',
            label: 'Please let us know your thoughts!',
            isRequired: false,
            isCustomerFeature: false,
            hint: null,
            placeholder: null,
            responseType: 'text',
            parentSurveyQuestionId: null,
            options: [],
          },
          {
            name: 'productGlucose',
            label: 'Did your glucose value increase more than 40mg/dL?',
            isRequired: false,
            isCustomerFeature: false,
            hint: null,
            placeholder: null,
            responseType: 'single',
            parentSurveyQuestionId: null,
            options: [
              {
                label: 'Yes',
                value: 1,
                isArchived: false,
              },
              {
                label: 'Unknown',
                value: -1,
                isArchived: false,
              },
              {
                label: 'No',
                value: 2,
                isArchived: false,
              },
            ],
          },
        ],
      },
    ],
  },
];
