COOKIE_SECRET=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/COOKIE_SECRET
PRISMA_ENCRYPT_KEY=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/PRISMA_ENCRYPT_KEY
SHIPHERO_API_KEY=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/shiphero_key
DATABASE_URL=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/DATABASE_URL
GCP_API_KEY=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/GCP_API_KEY
GOOGLE_CLIENT_ID=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/GOOGLE_CLIENT_SECRET
KLAVIYO_API=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/KLAVIYO_API
KLAVIYO_POTENTIAL_CUSTOMER_LIST=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/KLAVIYO_POTENTIAL_CUSTOMER_LIST
KLAVIYO_POTENTIAL_CUSTOMER_PRACTITIONER_LIST=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/KLAVIYO_POTENTIAL_CUSTOMER_PRACTITIONER_LIST
NEW_RELIC_LICENSE_KEY=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/NEW_RELIC_LICENSE_KEY
SENTRY_DSN=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/SENTRY_DSN
SERVER_URL=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/SERVER_URL
SHIPHERO_API_REFRESH_TOKEN=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/SHIPHERO_API_REFRESH_TOKEN
SHOPIFY_API_PASSWORD=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/SHOPIFY_API_PASSWORD
SHOPIFY_STOREFRONT_TOKEN=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/SHOPIFY_STOREFRONT_TOKEN
TERRA_API_KEY=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/TERRA_API_KEY
TERRA_DEV_ID=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/TERRA_DEV_ID
TWILIO_ACCOUNT_SID=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/TWILIO_AUTH_TOKEN
TWILIO_SERVICE_SID=projects/${{ secrets.DEV_SECRET_MANAGER_PROJECT_ID }}/secrets/TWILIO_SERVICE_SID
